### ISSUE TITLE
Need to add UPPERCASE letters here

### ISSUE THREAD

**Issue by olegabr** [web3p/ethereum-util#3]
https://github.com/web3p/ethereum-util/blob/8736ef0c4b40f9e4aa060cf8836a4f24c5072249/src/Util.php#L130

This code prevents usage of addresses in a canonical form with uppercase letters in address, like this one: `0x476Bb28Bc6D0e9De04dB5E19912C392F9a76535d`

**Comment by sc0Vu** [comment]
Hi,

Just found that https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

So we need to support uppercase and lowercase like `0xa-fA-F0-9` in this library.
